### ISSUE TITLE
Option for exporting/access information in real time 

### ISSUE THREAD

**Issue by stamparm** [enisaeu/ecsc-gameboard#10]
Export of the scoreboard in different formats (JSON/XML, etc.) For integration with other systems

**Comment by stamparm** [comment]
![foobar7](https://user-images.githubusercontent.com/921555/63603351-ca060000-c5c9-11e9-90ab-7e75385ce5fc.png)

![foobar8](https://user-images.githubusercontent.com/921555/63603358-cd00f080-c5c9-11e9-8eea-58bf8157c206.png)

**Comment by belmontemartin** [comment]
On the last version I cannot access to the xml (JSON ok)

**Comment by stamparm** [comment]
@belmontemartin Firefox stopped properly rendering XML documents because of XY reason (known "thingy" in Firefox). Please open ".../scores.xml" either in Chrome OR just press "View Page Source" inside Firefox (when accessing that same page)
