### ISSUE TITLE
Chat improvements

### ISSUE THREAD

**Issue by stamparm** [enisaeu/ecsc-gameboard#11]
Chat sometimes provided too much information, was easy to lost information.
Separation between Announcement chats, General chat, team chat (?)

**Comment by stamparm** [comment]
![foobar2](https://user-images.githubusercontent.com/921555/63602827-a2fafe80-c5c8-11e9-986f-b287e9c977f2.png)

**Comment by belmontemartin** [comment]
Related, see #15

**Comment by belmontemartin** [comment]
Hi,

would be possible to get a message on "general" chat when a there is a notification? (either the message itself or a link to the tab)

**Comment by stamparm** [comment]
@belmontemartin done:

![4](https://user-images.githubusercontent.com/921555/64709403-78f57780-d4b6-11e9-8735-82949d466f19.png)
