### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by stamparm** [enisaeu/ecsc-gameboard#14]
`Ability to create and get reports (exportable in CSV or other format) that includes different information about the resolution of the contracts (i.e: Analysis Time per task and other analysis information)`

**Comment by stamparm** [comment]
![foobar](https://user-images.githubusercontent.com/921555/63602729-6929f800-c5c8-11e9-8cff-9677c0799e14.png)

**Comment by belmontemartin** [comment]
To have the possibility to filter and download it.

**Comment by stamparm** [comment]
@belmontemartin Downloading is already available through `/stats.xml` (from last revision) and `/stats.json`:

![1](https://user-images.githubusercontent.com/921555/64120832-93846e00-cd9d-11e9-87a6-3663216b2903.png)

---

![2](https://user-images.githubusercontent.com/921555/64120833-93846e00-cd9d-11e9-8484-401c1b522aea.png)
