### ISSUE TITLE
Accessing chats and scores on browser tabs

### ISSUE THREAD

**Issue by belmontemartin** [enisaeu/ecsc-gameboard#15]
Have the possibility to access on a independent browser tab to the different chats and charts/scoreboards, in order to be show on different screes during the event.

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/64703717-4bf09700-d4ad-11e9-900a-740d62ca86cf.png)
---
![2](https://user-images.githubusercontent.com/921555/64703718-4bf09700-d4ad-11e9-8831-9c919271e049.png)

**Comment by stamparm** [comment]
![3](https://user-images.githubusercontent.com/921555/64704047-e51fad80-d4ad-11e9-878e-b5c9752e33c6.png)
