### ISSUE TITLE
[SPAM] MySQL credentials are hardcoded

### ISSUE THREAD

**Issue by icedevml** [enisaeu/ecsc-gameboard#17]
Either in Docker or by running a script natively, MySQL credentials are hardcoded to:
```php
    define("MYSQL_SERVER", "localhost");
    define("MYSQL_USERNAME", "ecsc");
    define("MYSQL_PASSWORD", "<blank>");
    define("MYSQL_DATABASE", "ecsc");
```
https://github.com/enisaeu/ecsc-gameboard/blob/master/html/includes/common.php#L3

There are no clear instructions in `README.md` that this password should be changed prior to installation and how to do it, so it is always well-known.

Perhaps some additional installation step should be added?

**Comment by stamparm** [comment]
Can do, but... By default MySQL instance is just exposed to the `localhost`, while in this case to the under-privileged user.

I am just trying to take away possible "I found a critical vulnerability" while there is none. Also, as I can see, you have a clear intention to go on a streak of raising "interesting" Issues, where without myself evaluating the severity of each, somebody could get random ideas

**Comment by icedevml** [comment]
Did I wrote `critical` anywhere? This doesn't let to immediately take the control over the whole machine hosting `ecsc-gameboard` but obviously this is some imperfection that does break *defense-in-depth* approach.

**Comment by psrok1** [comment]
There is also missing shell escape here: https://github.com/enisaeu/ecsc-gameboard/blob/master/html/includes/action.php#L64

Once again, it's not a `critical vulnerability` because value comes from trusted source, but there is implicit limit on set of characters that can be used as a password.

According to "spam" - whole project is open-source, so what's wrong in letting the community to find possible bugs for you?

**Comment by stamparm** [comment]
To be honest, people that compartmenise LAMP components (as in #16) really do take security in depth approach. Hence, I'll assess this and similar issues from you guys ASAP

**Comment by stamparm** [comment]
@psrok1 about the pointed missing shell escape - I am speechless. You have only constants in there.. Nevermind. Sorry guys, I'll just let you do your best.

**Comment by icedevml** [comment]
> really do take defense-in-depth approach

Are you sure that leaving default passwords for MySQL (as I see both `ecsc` user and `root`) is a part of defense-in-depth approach?

PS. The reason why I'm reviewing this is that I was obligated to present the operation the gameboard for one of the national teams during the pre-ECSC workshops. While setting it up, I was a little bit woried about multi-service Docker container, so I started to look inside.

I was even about to make some PRs, though I got discouraged as my ticket was tagged as `spam` and I was accused of `trolling` by telling about good practices o_O

Nevermind, I'm not taking your time anymore.

**Comment by stamparm** [comment]
There was no need to close this down. I'll do a change MySQL password prompt.

Word of advice for both of you. When you do a security code review, you do it throughly in hope to find a severe one. With the severe one, you have a hedge in the discussion. Period. In this kind of cases, when you haste to find anything remotely suspicious, while ignoring the rest, you'll just make a conflicting (cringe) situation, especially if the developer has some knowledge in the "security" department. 

So, please, I would like you to ask to continue and make a proper review and present worthy results.
