### ISSUE TITLE
Guess lockout infinite loop

### ISSUE THREAD

**Issue by icedevml** [enisaeu/ecsc-gameboard#19]
What is the exact purpose of this code in [html/index.php](https://github.com/enisaeu/ecsc-gameboard/blob/4a26249d635fde2fea9e4f759ec87b1a1c6dbd3a/html/index.php)?

```php
                    if ($_SESSION["last_wrong_counter"] >= intval(getSetting("guess_lockout"))) {
                        logMessage("Guess lockout", LogLevel::WARNING, "Potential brute-force detected");
                        while (true) {
                            sleep(10);
                        }
                    }
```

This `while (true)` would run till the expiration of `max_time_limit` counter which is set in `php.ini` (default: 30 seconds). The `setup.sh` script is installing the `libapache2-mod-php` which requires Apache to run in `prefork` mode, so AFAIR by default it could run up to 256 simultaneous workers. If I got everything right, doesn't it mean that if you send 256 flags while having a "guess lockout" on your session then the whole server would die for a half minute?

Sometimes CTF people happen to run some shady flag-brute-forcing scripts so the abovementioned DoS attack could be even done by mistake.

**Comment by stamparm** [comment]
1) Will rewrite it, though, you have wrong assumptions here. First of all, anti-CSRF tokens are used. Not bullet-proof, but a good first line of defense against "scripting". Second of all, `modevasive` is used, which means that you would have bad time performing "whole server would die for a half minute"
2) As said before, please don't overhype things, especially if you have somebody that can actually evaluate your claims

**Comment by stamparm** [comment]
p.s. opened this moment around 50 different tabs (with same authenticated session cookie) after a "guess lockout". All of them "wait". Workers status (`apachectl status`):

![foobar](https://user-images.githubusercontent.com/921555/65133584-24e11a80-da03-11e9-947d-9a5545b3bb50.png)

QED - you can't just simply "if you send 256 flags while having a "guess lockout" on your session then the whole server would die for a half minute". As said, please be real in your issues

**Comment by stamparm** [comment]
With the latest commit/revision that `sleep` is replaced by an abrupt sign out (taking back the user to the login screen)

**Comment by stamparm** [comment]
Anyway, thank you for raising the issue. The resulting "patch" should be a better way how to deal in similar cases
