### ISSUE TITLE
Un-hide hidden notifications

### ISSUE THREAD

**Issue by peterhuerlimann** [enisaeu/ecsc-gameboard#21]
Is there a way to un-hide/view once hidden notifications?

**Comment by stamparm** [comment]
With the latest commit/revision there will be a button to do this at the bottom of notifications (if the possibility to hide notification is [enabled](https://github.com/enisaeu/ecsc-gameboard/blob/master/html/includes/common.php#L21) in the first place):

![foobar](https://user-images.githubusercontent.com/921555/66124304-51408d80-e5e4-11e9-9ca7-70a3ad2d228a.png)
