### ISSUE TITLE
Security Issue: Edit Mask of other country

### ISSUE THREAD

**Issue by floyd-fuh** [enisaeu/ecsc-gameboard#23]
By using the following request, with a valid session ID, I get the mask to edit the details of france in the response, although I'm logged-in as Liechtenstein.

```
POST /includes/rankings.php HTTP/1.1
Host: board.ecsc.eu
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://board.ecsc.eu/includes/rankings.php
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 23
Connection: close
Cookie: PHPSESSID=foobarbaz

login_name=france&edit=
```

Response includes:

`<input name="email" value="A<REDACTED>.fr"`

I guess you forgot the isAdmin() call. However, it seems that editing the details is not possible afterwards. But extracting all the emails is.

![Screenshot 2019-10-03 at 12 58 45](https://user-images.githubusercontent.com/1428689/66122464-07ee3f00-e5e0-11e9-90fd-a0728a6e7362.png)

**Comment by stamparm** [comment]
A) `I guess you forgot the isAdmin() call` <- correct
B) Nice finding

**Comment by floyd-fuh** [comment]
Btw. there are several ways to prevent people from accessing "include" php files directly, for example as discussed on https://stackoverflow.com/questions/409496/prevent-direct-access-to-a-php-include-file . Maybe you can add that as an additional line of defense in all the files in the include directory. Just an idea.

**Comment by stamparm** [comment]
@floyd-fuh but you can't access `includes` directory directly. Everything goes through a combination of `mod_rewrite` which redirects all requests (except robots.txt, favicon.ico, files/, resources/) to `index.php`. Then, inside the `index.php` there is a custom [handling](https://github.com/enisaeu/ecsc-gameboard/blob/master/html/index.php#L33-L36) of all requests.

Basically, everything outside the [VALID_PAGES](https://github.com/enisaeu/ecsc-gameboard/blob/master/html/includes/common.php#L90) is just redirected to the front page

**Comment by floyd-fuh** [comment]
Ah, yes, haven't seen the mod_rewrite, thanks for clarification. So my comment is invalid (except maybe for the unlikely case that .htaccess is not working correctly)
