### ISSUE TITLE
Limiting length of chat/private messages

### ISSUE THREAD

**Issue by peterhuerlimann** [enisaeu/ecsc-gameboard#24]
Is there a setting to limit length of chat/private messages globally or for teams only?

At the moment quite large texts (I haven't tested it too much, but from what I figured probably all a TEXT field in the database can hold) can be posted. It's frankly not really a load and storage issue, but could rather lead to unwanted disturbances in gameplay, if someone spams the chats and / or  private messages with e.g. especially extensive walls of texts.

**Comment by stamparm** [comment]
With the latest commit, hard-cap (for non-admin users) is 128 chars for chat messages and 256 chars for private messages.
