### ISSUE TITLE
Dynamic Scoring implementation

### ISSUE THREAD

**Issue by belmontemartin** [enisaeu/ecsc-gameboard#3]
Implementation of dynamic scoring for the contracts

**Comment by stamparm** [comment]
![foobara](https://user-images.githubusercontent.com/921555/63603856-ba3aeb80-c5ca-11e9-85b8-66932c7d553d.png)
![foobarb](https://user-images.githubusercontent.com/921555/63603857-bad38200-c5ca-11e9-9b48-93b058dd5520.png)
![foobarc](https://user-images.githubusercontent.com/921555/63603858-bad38200-c5ca-11e9-8838-904655a78d55.png)

p.s. to be further discussed (currently it seems more than "usable" - either decay per solve and/or decay per hour - in each case, penalty is being calculated based on a defined "decay" coefficient(s))
p.p.s. penalized/decayed scored is automatically being displayed in contracts/tasks and evaluated during a ranking table calculation

**Comment by BitSentinel** [comment]
You should also have a minimum value for the score. Also, I recommend to provide some simulations for different score decays - eg. how many solves are needed to reach the minimum threshold if DYNAMIC_DECAY_PER_SOLVE is 0.2.

**Comment by stamparm** [comment]
Different scenarios / simulations (note: `effective_score = ORIGINAL_SCORE - penalty`):

A)

```
DYNAMIC_DECAY_PER_HOUR = 0
DYNAMIC_DECAY_PER_SOLVE = 0.05
DYNAMIC_DECAY_MAX_PENALTY = 0.5
ORIGINAL_SCORE = 1000  # i.e. cash

# per each solution / solve
effective_scores = [1000.0, 950.0, 900.0, 850.0, 800.0, 750.0, 700.0, 650.0, 600.0, 550.0, 500.0, 500.0, 500.0, ...]
```

B)

```
DYNAMIC_DECAY_PER_HOUR = 0.05
DYNAMIC_DECAY_PER_SOLVE = 0
DYNAMIC_DECAY_MAX_PENALTY = 0.2
ORIGINAL_SCORE = 1000  # i.e. cash

# per each hour
effective_scores = [1000.0, 990.0, 980.0, 970.0, 960.0, 950.0, 940.0, 930.0, 920.0, 910.0, 900.0, 900.0, 900.0, 900.0, ...]
```

**Comment by stamparm** [comment]
p.s. simple "simulation" python script:

```
DYNAMIC_DECAY_PER_HOUR = 0.01
DYNAMIC_DECAY_PER_SOLVE = 0
DYNAMIC_DECAY_MAX_PENALTY = 0.1
ORIGINAL_SCORE = 1000  # i.e. cash

results = []
solves = 0
penalty = 0
hours= 0

while True:
    penalty = 0

    if DYNAMIC_DECAY_PER_HOUR:
        penalty += ORIGINAL_SCORE * hours * DYNAMIC_DECAY_PER_HOUR

    if DYNAMIC_DECAY_PER_SOLVE:
        penalty += ORIGINAL_SCORE * solves * DYNAMIC_DECAY_PER_SOLVE

    if penalty > DYNAMIC_DECAY_MAX_PENALTY * ORIGINAL_SCORE:
        break
    else:
        penalty = min(penalty, DYNAMIC_DECAY_MAX_PENALTY * ORIGINAL_SCORE)

    results.append(ORIGINAL_SCORE - penalty)

    hours += 1
    solves += 1

print results
```

**Comment by BitSentinel** [comment]
Thanks! We had the chance to check the process. This is not the expected behaviour. 

Right now, each solver is rewarded with the new updated score meaning that first solver will receive 500$ for a challenge, while the next ones will get significantly less.

The expected behaviour is to reward all solvers with the same number of points and update the score based on the total number of solvers (using the proposed formula).
