### ISSUE TITLE
Use a proper captcha

### ISSUE THREAD

**Issue by grzegorz225** [enisaeu/ecsc-gameboard#31]
The current captcha is a joke... It is made according to an online tutorial for beginners... https://github.com/enisaeu/ecsc-gameboard/blob/a557e9fb8339ce322f0a9aae5992828d6e48a862/html/includes/captcha.php#L7
The current captcha can be solved easily by OCR software or simple image processing techniques.

Do not reinvent the wheel - either use a proper captcha library(not a good idea) or just use google recaptcha like most sites.

**Comment by NieDzejkob** [comment]
@stamparm Did you forget to push the change that fixes this?

**Comment by stamparm** [comment]
No. Just waiting for your "smart" pull request. You guys are rocking. Good luck tomorrow!
