### ISSUE TITLE
Add "Rules" button to link to rules document

### ISSUE THREAD

**Issue by peterhuerlimann** [enisaeu/ecsc-gameboard#32]
I propose adding a "Rules" button, for people to access the official rules document located at https://ecsc.eu/about/ecscrules.pdf/download, from within the gameboard.

**Comment by stamparm** [comment]
![screenshot](https://user-images.githubusercontent.com/921555/66784613-44bd0e80-eedb-11e9-8195-ca4b7874c429.png)
