### ISSUE TITLE
Option to postpone the end of the event for specific teams

### ISSUE THREAD

**Issue by bartusek27** [enisaeu/ecsc-gameboard#37]
Hello @stamparm @belmontemartin ,

we are proposing adding a feature that we could use to ensure fair conditions in case of any problem with the competition and scoring. This feature would contain a `checkbox` and a `datetime` inputs for each of the teams that would change their end of the competition. If checked and filled in a way that `datetime` is higher than the default ending date of the competition then this team will be allowed to operate the gameboard and download challenges and submit their flags until the set date.

**Example:**
If the team was delayed by any problems (technical, rule check, challenge problems etc.), we can add them another e.g. 10 minutes above the main ending date and time of the event.

Feel free to reach out to me in case of any questions.

_Thanks,
Jiří from ECSC 2021 team_

**Comment by bartusek27** [comment]
Hello @stamparm,

what's the status on this issue? The date for us running the portal for the teams to test it out is closing on and we need to test the platform ourselves too.

Thank you and have a nice day!

**Comment by stamparm** [comment]
i will do it, though, I expect big problems here. so, i am currently implementing the `Start`/`Stop` feature in the admin area. furthermore, there are optional start and end time boxes in admin area (too). adding this to individual teams will for sure introduce the mess (<- e.g. admin won't know the priorities of those controls for sure; even i am not sure about the priorities). anyhow, will implement, though, i expect that as in every event i'll be there to help you run this in the first place

**Comment by liskaant** [comment]
Hi @stamparm. I agree that this might caouse a lot of confusion in priorities of controlls. Might I offer an alternative solution:

Add and ability to hide a specific challange for a specific team. A very siple interface (maybe a table of checkboxes). This should not have any confusion in priorities. Ii would not be automatic but fast enough for manual setup in case it is nescessary to postpone the end of the event only for specific teams. This would solve the root issue from my prespective.

Kind regards,
Antonin Liska

**Comment by stamparm** [comment]
@liskaant doable. will implement it these days and let you know

**Comment by stamparm** [comment]
@liskaant started to think about and implement this "option" and suddenly realized that "per task" is actually more problematic than to give bonus time for individual teams. Main issue is the end of the event, which halts even the login for all teams. Thus, I decided to implement the "Extra time" feature to individual teams

**Comment by stamparm** [comment]
@liskaant with the latest revision, there is an extra per-team option `End time (override)`. It has the top priority in the time checks for login and contract/task logic. It should give you the ability that you require:

![1](https://user-images.githubusercontent.com/921555/127934910-fa3ca895-d076-4acb-bc96-67eab43a3f7e.png)

**Comment by liskaant** [comment]
Hi @stamparm,

> started to think about and implement this "option" and suddenly realized that "per task" is actually more problematic than to give bonus time for individual teams. Main issue is the end of the event, which halts even the login for all teams.

I was thinking more along the lines of using the hiding of challanges as a form of ending the event. Not setting the end time but hiding all challanges except a few specific challange-team combinations. That was my thinking, however your implementation solves the problem.

> with the latest revision, there is an extra per-team option End time (override). It has the top priority in the time checks for login and contract/task logic. It should give you the ability that you require:

Thank you, I did a quick test and it works well. There is however something not so obvious from users prespective: The override only applies when global end time is set and is in the past, which is not explicitly stated in the UI and frankly doesnt make much sense to me why it would not be possible to set end time for one team without having to specify global end time, or why it would not be possible to shorten the end time for a specific team. At least that is how I would imagine an "override" working.

It is not necessary to address this, but I belive it may become a source of confusion in the future.

Kind regards,
Antonin Liska

**Comment by stamparm** [comment]
@liskaant with latest revision/commit, per-team end-time has the highest priority (i.e. end prior to OR extend after <- both work now). Thus, your request from previous message should be fulfilled now
