### ISSUE TITLE
 Improvements on flags introduction

### ISSUE THREAD

**Issue by belmontemartin** [enisaeu/ecsc-gameboard#4]
Regarding to this, there were some request:

 

-        Lower case/upper case detection (maybe optional for some contracts)

-        In general:  Flag Types: Static, Regex, Date time, Multiple Choice, File 

-        (specific request): Requires ability to allow for many permutations of the same answer.  e.g. If the answer has four words that they can be inserted in any order and still be correct.

**Comment by belmontemartin** [comment]
Each contract should give us a specific pattern for flag format, something like:
•	ECSC{...}
•	flag{file content .pass}
•	flag{XXXXXXXXXXXXXXXXXXXX}
•	flag{md5(comand)}
If the challenge/contract has a flag with date and | or time format, it is important to clearly specify the flag format and the placement of the date and time, ie  flag{dd/mm/yyyy hh: mm}

**Comment by stamparm** [comment]
Note: "multiple choice" is i) not appropriate for CTF-like challenges, ii) could easily be "guessed" with couple of requests, iii) usual FLAGs format is far superior also because of easy removal of a guessing-space

**Comment by stamparm** [comment]
![foobar6](https://user-images.githubusercontent.com/921555/63603177-5d8b0100-c5c9-11e9-855e-a945040872de.png)
