### ISSUE TITLE
Improved system logging capabilities and Event Triggering 

### ISSUE THREAD

**Issue by belmontemartin** [enisaeu/ecsc-gameboard#5]
I think this is useful for integrating and capturing events (so for example we can notify which teams are working on which task or when a team complete a contract, etc…)

In general:

-	Capture of errors, flags introduced system information, etc…

-	Notification when certain event occurs (ie some team solves a king of the hill flag, this send a message or trigger certain event)

**Comment by stamparm** [comment]
![foobar5](https://user-images.githubusercontent.com/921555/63603094-2caacc00-c5c9-11e9-9e77-1d51841524b5.png)

**Comment by belmontemartin** [comment]
Andrei commented the possibility of filtering.

I would also add the possibility to dump it to a file in the system, in order to be easily captured.

**Comment by stamparm** [comment]
p.s. Filtering/pagination has been already implemented
