### ISSUE TITLE
Time Management

### ISSUE THREAD

**Issue by stamparm** [enisaeu/ecsc-gameboard#6]
Optional exact start time and end time

**Comment by stamparm** [comment]
![foobar4](https://user-images.githubusercontent.com/921555/63603039-0c7b0d00-c5c9-11e9-90bc-8517b6269647.png)

**Comment by belmontemartin** [comment]
It would be interested to have start/end time for specific contracts (they will be hidden until that specific date).

Also other characteristics can be included for specific contracts (ie: attempts)

**Comment by stamparm** [comment]
Start/end time for specific contracts will most probably been implemented by some (easy to use) mass hide/show in the next platform's iteration.
